# Camera Serial Numbers
left_camera_serial: 17473641
right_camera_serial: 17403017

# Camera Calibration files
left_camera_info_url: package://spinnaker_driver_ros/cfg/left_camera_5MP.yaml
right_camera_info_url: package://spinnaker_driver_ros/cfg/right_camera_5MP.yaml

# Camera Configuration
# Can be reconfigured in SW triggering
# In HW triggering, to make sure that the triggers will all be implemented
# the frame rate and exposure time should follow:
# frame_rate <= 1.0 / (0.014 + exposure_time * 1.0e-6) -> For the 5MP cameras
frame_rate: 5.0
exposure_time: 2000.0 # in microseconds
gain: 0.0

# Resize images before publishing in ROS
# Factor to devide width and height by
# NOT USED in HW triggering
resize_factor: 1.0